services:
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    command: server /data --console-address ":9001"
    container_name: minio_aula
    networks:
      - app_network
    volumes:
      - minio_data:/data
    ports:
      - "9002:9000"  # Porta do serviço S3
      - "9001:9001"  # Porta do console de administração
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minha_senha
      MINIO_BROWSER_REDIRECT_URL: http://minio:9001
      MINIO_SERVER_URL: http://minio:9000
    restart: always

volumes:
  minio_data:

networks:
  app_network:
    external: true
